
baseURL = "https://rainleave.github.io/"
theme = "LoveIt"
title = "My Hugo Blog"

[permalinks]
  posts = "/posts/:year/:month/:day/:title/"
# baseURL = 'https://example.org/'
languageCode = 'en-us'
# title = 'My New Hugo Site'
